In [193]:
import pandas as pd
import numpy as np

In [194]:
df=pd.read_csv('customer_data.csv')

In [195]:
df.head()

id  age  gender  income   education region loyalty_status  \
0   1   27    Male   40682    Bachelor   East           Gold   
1   2   29    Male   15317     Masters   West        Regular   
2   3   37    Male   38849    Bachelor   West         Silver   
3   4   30    Male   11568  HighSchool  South        Regular   
4   5   31  Female   46952     College  North        Regular   

  purchase_frequency  purchase_amount product_category  promotion_usage  \
0           frequent            18249            Books                0   
1               rare             4557         Clothing                1   
2               rare            11822         Clothing                0   
3           frequent             4098             Food                0   
4         occasional            19685         Clothing                1   

   satisfaction_score  
0                   6  
1                   6  
2                   6  
3                   7  
4                   5

In [196]:
df.iloc[:,2:]

gender  income   education region loyalty_status purchase_frequency  \
0        Male   40682    Bachelor   East           Gold           frequent   
1        Male   15317     Masters   West        Regular               rare   
2        Male   38849    Bachelor   West         Silver               rare   
3        Male   11568  HighSchool  South        Regular           frequent   
4      Female   46952     College  North        Regular         occasional   
...       ...     ...         ...    ...            ...                ...   
99995  Female   19691     College   West        Regular         occasional   
99996    Male   17428  HighSchool  South        Regular               rare   
99997    Male   13222     College   West        Regular           frequent   
99998  Female   40093    Bachelor   West        Regular           frequent   
99999  Female   22249     College   West         Silver               rare   

       purchase_amount product_category  promotion_usage  satisfaction_score  
0                18249            Books                0                   6  
1                 4557         Clothing                1                   6  
2                11822         Clothing                0                   6  
3                 4098             Food                0                   7  
4                19685         Clothing                1                   5  
...                ...              ...              ...                 ...  
99995             7075           Health                0                   7  
99996             6873           Health                0                   5  
99997             5152         Clothing                0                   5  
99998            16312           Health                1                   5  
99999             9426           Health                0                   6  

[100000 rows x 10 columns]

In [197]:
df.drop(columns=['income','purchase_amount','promotion_usage','satisfaction_score'],inplace=True)

In [198]:
df.head()

id  age  gender   education region loyalty_status purchase_frequency  \
0   1   27    Male    Bachelor   East           Gold           frequent   
1   2   29    Male     Masters   West        Regular               rare   
2   3   37    Male    Bachelor   West         Silver               rare   
3   4   30    Male  HighSchool  South        Regular           frequent   
4   5   31  Female     College  North        Regular         occasional   

  product_category  
0            Books  
1         Clothing  
2         Clothing  
3             Food  
4         Clothing

In [199]:
df.drop(columns=['id','age'],inplace=True)

In [200]:
df.head()  
# gender -> nominal data so ethe one hot encoder use hoega but odee li transformer chahida hunda jeda hale tak mae nhi sikhya so drop that cols which are nominal

gender   education region loyalty_status purchase_frequency  \
0    Male    Bachelor   East           Gold           frequent   
1    Male     Masters   West        Regular               rare   
2    Male    Bachelor   West         Silver               rare   
3    Male  HighSchool  South        Regular           frequent   
4  Female     College  North        Regular         occasional   

  product_category  
0            Books  
1         Clothing  
2         Clothing  
3             Food  
4         Clothing

In [201]:
df.drop(columns=['gender','region','product_category'],inplace=True)

In [202]:
df.head()
# hun pehle do columns are ordinal data because  masters > Bachelor > college > highschool  |  gold > silver > regular  ->ordinalencoding

#purchase_freq is label means output so label encoder 

education loyalty_status purchase_frequency
0    Bachelor           Gold           frequent
1     Masters        Regular               rare
2    Bachelor         Silver               rare
3  HighSchool        Regular           frequent
4     College        Regular         occasional

In [203]:
df['education'].unique() ,df['loyalty_status'].unique(),df['purchase_frequency'].unique()

(array(['Bachelor', 'Masters', 'HighSchool', 'College'], dtype=object),
 array(['Gold', 'Regular', 'Silver'], dtype=object),
 array(['frequent', 'rare', 'occasional'], dtype=object))

In [204]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(df.drop(columns=['purchase_frequency']) , df['purchase_frequency'] , test_size=0.3)

In [205]:
x_train

education loyalty_status
32849     College        Regular
37840     Masters         Silver
62328     College         Silver
42866    Bachelor           Gold
65931  HighSchool        Regular
...           ...            ...
34336     College         Silver
32152     College         Silver
32481    Bachelor        Regular
94421  HighSchool        Regular
57064     College         Silver

[70000 rows x 2 columns]

In [206]:
y_train

32849    occasional
37840          rare
62328    occasional
42866          rare
65931      frequent
            ...    
34336      frequent
32152          rare
32481          rare
94421          rare
57064    occasional
Name: purchase_frequency, Length: 70000, dtype: object

In [207]:
from sklearn.preprocessing import OrdinalEncoder

oe=OrdinalEncoder(categories=[['HighSchool' ,'College' ,'Bachelor' ,'Masters'] , ['Regular',"Silver",'Gold']])
# highschool->0  college->1   regular->0  apne app ainve karke values assign kardega



In [208]:
oe.fit(x_train)

OrdinalEncoder(categories=[['HighSchool', 'College', 'Bachelor', 'Masters'],
                           ['Regular', 'Silver', 'Gold']])

In [209]:
x_train_transform = oe.transform(x_train)
x_test_transform = oe.transform(x_test)

In [210]:
x_train_transform

array([[1., 0.],
       [3., 1.],
       [1., 1.],
       ...,
       [2., 0.],
       [0., 0.],
       [1., 1.]])

In [211]:
x_test_transform

array([[1., 0.],
       [0., 0.],
       [3., 1.],
       ...,
       [1., 1.],
       [3., 0.],
       [1., 1.]])

In [212]:
x_train_transform=pd.DataFrame(x_train_transform,columns=x_train.columns)

In [213]:
x_train_transform.sample(10)

education  loyalty_status
14937        1.0             0.0
69972        3.0             1.0
43994        1.0             0.0
29014        1.0             1.0
66919        2.0             1.0
48106        2.0             0.0
54322        1.0             0.0
33536        1.0             0.0
62625        0.0             2.0
43882        3.0             2.0

In [214]:
# now for output column
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()      # ethe ni lod pass karn li kinu kedi value dvani aa eh ape kardega

le.fit(y_train)


y_train_transform = le.transform(y_train)
y_test_transform = le.transform(y_test)


In [215]:
y_train_transform

array([1, 2, 1, ..., 2, 2, 1])

In [217]:
y_train_transform=pd.DataFrame(y_train_transform , columns=['loyalty_status'])

In [219]:
y_train_transform

loyalty_status
0                   1
1                   2
2                   1
3                   2
4                   0
...               ...
69995               0
69996               2
69997               2
69998               2
69999               1

[70000 rows x 1 columns]