<a href="https://colab.research.google.com/github/Rubal-code/Machine-Learning/blob/main/feature_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd


In [2]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()

In [4]:
bow=cv.fit_transform(df['text'])

In [5]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [7]:
bow[0].toarray()

array([[1, 0, 1, 1, 0]])

In [8]:
bow[1].toarray()

array([[2, 0, 0, 1, 0]])

In [9]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 1, 1]])