<a href="https://colab.research.google.com/github/Rubal-code/Machine-Learning/blob/main/feature_extraction_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd


In [11]:
df=pd.DataFrame({'text':['people watch campusx','campusx watch campusx','people write comment','campusx write comment'],'output':[1,1,0,0]})

In [12]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
cv1=CountVectorizer(ngram_range=(2,2))

In [13]:
bow=cv.fit_transform(df['text'])

In [14]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [15]:
bow[0].toarray()

array([[1, 0, 1, 1, 0]])

In [16]:
bow[1].toarray()

array([[2, 0, 0, 1, 0]])

In [17]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 1, 1]])

In [18]:
cv1.fit_transform(df['text'])

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (4, 6)>

In [19]:
print(cv1.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [20]:
cv.transform(["campusx watch and write comment of campusx"]).toarray()

array([[2, 1, 0, 1, 1]])