In [18]:
import pandas as pd
import numpy as np
from sklearn.metrics import f1_score,recall_score,precision_score,confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier



In [19]:
df=pd.read_csv('heart.csv')

In [20]:
df.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
6,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
7,55,1,0,160,289,0,0,145,1,0.8,1,1,3,0
8,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0
9,54,1,0,122,286,0,0,116,1,3.2,1,2,2,0


In [21]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [22]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()


In [23]:
clf1.fit(X_train,y_train)
y_pred1 = clf1.predict(X_test)

c:\Users\hp\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [24]:
clf2.fit(X_train,y_train)
y_pred2 = clf2.predict(X_test)

In [25]:
confusion_matrix(y_test,y_pred1)

array([[83, 22],
       [10, 90]])

In [26]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



,0,1
0,83,22
1,10,90


In [27]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix



,0,1
0,101,4
1,0,100


In [28]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [29]:
result

,Actual Label,Logistic Regression Prediction,Decision Tree Prediction
546,0,0,0
980,1,1,1
908,0,0,0
577,0,0,0
846,1,1,1
...,...,...,...
922,1,1,1
832,1,1,1
451,1,1,1
775,1,1,1


In [30]:
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

Precision -  0.8035714285714286
Recall -  0.9
F1 score -  0.8490566037735849


In [31]:
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

Precision -  0.9615384615384616
Recall -  1.0
F1 score -  0.9803921568627451


In [32]:
precision_score(y_test,y_pred2,average=None)

array([1.        , 0.96153846])

In [33]:
recall_score(y_test,y_pred2,average=None)

array([0.96190476, 1.        ])

In [34]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.89      0.79      0.84       105
           1       0.80      0.90      0.85       100

    accuracy                           0.84       205
   macro avg       0.85      0.85      0.84       205
weighted avg       0.85      0.84      0.84       205

