**with help of sklearn libraries we will calculate r2 score**

In [85]:
import numpy as np
from sklearn.datasets import load_diabetes

In [86]:
X,y=load_diabetes(return_X_y=True)

In [87]:
X.shape # input columns

(442, 10)

In [88]:
y.shape  # output columns

(442,)

In [89]:
X  # 2d numpy array

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [90]:
y  # 1d numpy array

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [91]:
from sklearn.model_selection import train_test_split



In [92]:
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [93]:
x_train.shape

(353, 10)

In [94]:
x_test.shape

(89, 10)

In [95]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

In [96]:
from sklearn.metrics import r2_score
r2_score(y_pred,y_test)

-0.015299458907063412

In [97]:
from sklearn.preprocessing import PolynomialFeatures
poly=PolynomialFeatures(degree=2)
x_poly=poly.fit_transform(X)
x_poly.shape      #this Polynomial Features are a way to make a linear model capture non-linear patterns.

(442, 66)

In [98]:
from sklearn.pipeline import make_pipeline
model=make_pipeline(poly,LinearRegression())
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
r2_score(y_pred,y_test)

0.27702986471939517

In [99]:
lr.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [100]:
lr.intercept_

np.float64(151.88331005254167)

**now we will make our linear regression**

In [117]:
class MERA_LR:
    def __init__(self):
        self.coef_=None
        self.intercept_=None


    def fit(self,x_train,y_train):
        x_train=np.insert(x_train,0,1,axis=1)   # np.insert(kide ch inert karna , kede index te karna , ki karna insert , column(1) or row(0)) we have done this because in the matrix X we have first column consisting 1 so we have to add that 1's manually

        # calculate coeff
        betas=np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train)  # B=(x^T x)^-1 x^T y   np.dot means multiply two things np.linalg.inv is used to solve the inverse
        self.intercept_=betas[0]
        self.coef_=betas[1:]

    def predict(self,x_test):
        y_pred=np.dot(x_test,self.coef_) + self.intercept_
        return y_pred


In [118]:
LR=MERA_LR()
LR.fit(x_train,y_train)

In [119]:
print(LR.coef_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]


In [120]:
print(LR.intercept_)

151.88331005254167


In [122]:
y_pred=LR.predict(x_test)

In [123]:
r2_score(y_pred,y_test)

-0.015299458907066743

In [ ]:
# class MERA_LR:
#     def __init__(self):
#         self.coef_=None
#         self.intercept_=None


#     def fit(self,x_train,y_train):
#         x_mean=np.mean(x_train)
#         y_mean=np.mean(y_train)

#         # coeff (B1)
#         num=np.sum((x_train - x_mean)*(y_train - y_mean))
#         den=np.sum((x_train - x_mean)**2)
#         self.coef_=num/den 

#         # intercept(Bo)                                      y=mx+c --> c=y-mx
#         self.intercept_=y_mean - self.coef_ * x_mean


#     def predict(self,x_test):
#         return self.intercept_ + self.coef_ * x_test
