In [1]:
import numpy as np
import pandas as pd

In [3]:
np.random.seed(23)  #In simple words:

# Without seed → random numbers change every time.

#With seed → random numbers stay the same every time (for the same seed).

In [ ]:
mu_vector1=np.array([0,0,0])       # means data centerd hoega
cov_mat1=np.array([[1,0,0],[0,1,0],[0,0,1]])    # spread equally 1  and 0 there is no corr between the axis
class1_sample=np.random.multivariate_normal(mu_vector1,cov_mat1,20)

In [6]:
df=pd.DataFrame(class1_sample,columns=['feature1','feature2','feature3'])
df['target']=1

In [8]:
mu_vector2=np.array([1,1,1])  
cov_mat2=np.array([[1,0,0],[0,1,0],[0,0,1]])    # spread equally 1  and 0 there is no corr between the axis
class2_sample=np.random.multivariate_normal(mu_vector2,cov_mat2,20)

In [9]:
df1=pd.DataFrame(class2_sample,columns=['feature1','feature2','feature3'])
df1['target']=0

In [12]:
df=pd.concat([df,df1],ignore_index=True)

In [13]:
df=df.sample(40)

In [15]:
df.head(3)

feature1  feature2  feature3  target
7   1.045371  0.538162  0.812119       1
27  2.682045  2.065423  0.394436       0
26  0.387819  0.263158 -0.195360       0

In [18]:
import plotly.express as px

fig=px.scatter_3d(df,x=df['feature1'],y=df['feature2'],z=df['feature3'],color=df['target'].astype('str'))
fig.show()

In [ ]:
# step 1) apply standard scaling 
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df.iloc[:,0:3]=scaler.fit_transform(df.iloc[:,0:3])

In [23]:
# step 2) finding covariance matrix
covariance_matrix=np.cov([df.iloc[:,0],df.iloc[:,1],df.iloc[:,2]])
print("covariance matrix : \n",covariance_matrix)

covariance matrix : 
 [[1.02564103 0.22384719 0.0090714 ]
 [0.22384719 1.02564103 0.03734827]
 [0.0090714  0.03734827 1.02564103]]


In [ ]:
# step 3) find eigen values and eigen vectors
eigen_values,eigen_vectors=np.linalg.eig(covariance_matrix)

In [25]:
eigen_values

array([1.25421994, 0.80000299, 1.02270014])

In [26]:
eigen_vectors

array([[-0.69539951, -0.69966624, -0.16397156],
       [-0.70431698,  0.7088789 , -0.03779285],
       [-0.14267836, -0.08920682,  0.98574085]])